### ISSUE TITLE
想下载你的易对1.2

### ISSUE THREAD

**Issue by jiespring** [mgenware/k-closest-elements#1]
我想使用你的易对1.2工具软件，但是你的博客mgenware无法访问下载页面。希望提高下载链接。

**Comment by mgenware** [comment]
@jiespring , 感谢反馈问题，我才发现mgenware域名无法访问了，可能又是由于备案问题。请发送邮件到: contact [at] mgenware.com 然后我单独发你一份。

**Comment by jiespring** [comment]
昨天就已发送邮件。没见你回复！

**Comment by mgenware** [comment]
@jiespring 刚刚回复了，不好意思，没有留意邮件通知😃
